# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    filter_sets:
        thumb:
            quality: 85
            filters:
                thumbnail:
                    size: [360, 230]
                    mode: outbound
        mid_size_formated:
            quality: 85
            filters:
                thumbnail:
                    size: [1280, 720]
                    mode: outbound
                    allow_upscale: true


    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
